language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn
  - npm config set spin false
  - npm install -g npm@^6.9.0
script:
  - yarn test-ci
  - yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "coK5iRr9GXeVUWs8sieus0wxuitPcUtB2HoH3EozRGbmE6hDt1/FpzbLtwePEEB/a5bZ4feid+Hbd9il3eaLMzs0mCpUXUnDe2sR0sT29k8uy2MJmunk8tGXK0To5o8XXZYePe+XADuOFyLHIbUwiFnZiLu5Ia21ze1ScQezWyr6ofrI+dhErfhZ6KwTcZK5Feh1mYLqb21e+0yuF0rXalAnvmQI3bIgC9++IFCgAZAlBjj6SsHjTeP0pbpoJYqriyWyx0fuyHxNsnlK+W4ElNUCQXYhsY6DVRM8WzwQKlhA5vat11LHPUfVMLbM7dlaqVowig57fsfTEs6b2FqVfteiNvWtSfvNJHIMpKFH+4GjXo+LhyBrbIxIE+BKO3XKgw5SRaCJ6myA6RP/5ZxxXjcG6bRmtUiX2LF2EAQ2sZf+G2+D+uajAhPHwC55YrSgHjrztP+aj5LAkH0rxR2CrmQYG0BS0gVp/hqqYGKF+U9TAkBrlRruo690pJJ95ZXJEeQd7YX+30vxgrtoglYXPqFIEsZTAX5pZ25wVtf6PE5oQAoswpRKSJe7DCmpiTbV9yvewbsnjAhaYMg3LSfjWu/4Y5Mo+NSdq/qukA9VjJGLtRPQfx6EP4H70fO0DjhzvHieQm1wiEBoc2NbY9IOdBqXWqiUIIjY1l0zUeHxVSg="
  file:
    - build/_output/enigma.wigt
    - build/_output/enigma-build-info.yml
  on:
    tags: true
    repo: ucfopen/enigma-materia-widget
notifications:
  slack:
    secure: "XQq2/KGdZEuu1JJMFkDVizZ+y47jdqt9JdmrftaCjkAKHdjK5/yxw6EZlCyYj+c9qa2Oa5M5XevIQvTdppcueSdUEaGrWF90zyLDXvfXO2ZPdRfTiNN4g0Al9ggDhYwxZznEMHZcvkYvQVGihUoEA4C8vcrDkz0WoobuDYbbNenzrp7aaS196Lg1G4pX9Td71DNws/4jzN/3fAqk9VkGwHRj0i3dZ+g7WjKwyYl1/I2DozY0fUNhQfYPJiGQwpypL4qhkUMERms65/IFwL29n1Lj3DVM58YbmLXFz+I7FaGK/sWdWz57xMsz/2jCctw2HQj4M6uvTbjXYbezqMrWC38q7cEnU5+SndlKvxW7KzBlS1Tt6FMnMG/ULSR0ZjtNIgABMeIiF5OHUiqwCQzzhAHnDi9n39LVXcFCK5BOvaYdBfliAbo0ZWg+6/bgSd5lz8hp4cRsc8jJMIMPnSMtgGaeelQj4pHiRzfoEcbae2ksL6kT1DNVstCYBOCmoDsPwbhrr6Ouf2TA5lpQ0UBM3/Lm+pRrVwX/VpqAsd1zb753LkguACeqBT0taLhtDCQ37apjtS6ArM/ROxrhPtbh/2BZNHCqTtQDWUAYnyKGi5nDNHjtdgwyQk57RTmm9EAXjvQAvubIGiVcmgJqDK9Qv4G/J2IEIV/9yTgHReYuZTw="
