language: node_js
node_js:
  - '6'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g npm@^5
script:
  - yarn test-ci
  - yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "coK5iRr9GXeVUWs8sieus0wxuitPcUtB2HoH3EozRGbmE6hDt1/FpzbLtwePEEB/a5bZ4feid+Hbd9il3eaLMzs0mCpUXUnDe2sR0sT29k8uy2MJmunk8tGXK0To5o8XXZYePe+XADuOFyLHIbUwiFnZiLu5Ia21ze1ScQezWyr6ofrI+dhErfhZ6KwTcZK5Feh1mYLqb21e+0yuF0rXalAnvmQI3bIgC9++IFCgAZAlBjj6SsHjTeP0pbpoJYqriyWyx0fuyHxNsnlK+W4ElNUCQXYhsY6DVRM8WzwQKlhA5vat11LHPUfVMLbM7dlaqVowig57fsfTEs6b2FqVfteiNvWtSfvNJHIMpKFH+4GjXo+LhyBrbIxIE+BKO3XKgw5SRaCJ6myA6RP/5ZxxXjcG6bRmtUiX2LF2EAQ2sZf+G2+D+uajAhPHwC55YrSgHjrztP+aj5LAkH0rxR2CrmQYG0BS0gVp/hqqYGKF+U9TAkBrlRruo690pJJ95ZXJEeQd7YX+30vxgrtoglYXPqFIEsZTAX5pZ25wVtf6PE5oQAoswpRKSJe7DCmpiTbV9yvewbsnjAhaYMg3LSfjWu/4Y5Mo+NSdq/qukA9VjJGLtRPQfx6EP4H70fO0DjhzvHieQm1wiEBoc2NbY9IOdBqXWqiUIIjY1l0zUeHxVSg="
  file:
    - build/_output/enigma.wigt
    - build/_output/enigma-build-info.yml
  on:
    tags: true
    repo: ucfopen/enigma-materia-widget
notifications:
  slack:
    secure: "Onizyp81mJjm/dAGMcAzty7fUH5eaLX3bDG9qBs9caj9Uw679Fi6313yjwHDOUQFwfApPVvMSKPLD06qqP1kzLMZfhiyH0dL4ifZZsXHUBuhTxT4kW7gt34jQ/zhHhuGZoYj5rk+RnqgmEK6p5c+cBT2eOvpxLpX9wtpDJHOJ2OzLzvG34LZDmV0DbYIeF/gOeTPGGR57CB7oTCxWiK6S1KrIJIZndppmbM3o/sY67Jz1aiIEiBfu/T6kXPfDX2VEtMP3dVEXf2gb/gEI2AeN4PdPwrY/Qy9EZMF4vlrayPiepew9ijphjZTQhY4VlcZg5BpAN6E6jQA5o4pHT3p9+WcGFe08oUM3uyKFesgPnQEcoMoDtDneSh2JVt4EdObWDuhyzP5m6tQWTesS7nCS6rZNsZrG8iiBVwd/GhJU+WsrYPAM1dJfNPECzYxNFmKNXFL4yyaN+thZEvDSbB3iTWNGYAq8CT4ICABSO70RiL6xTcfcbzTW84AMuNFO58loNjPVEnf9xuogRUzgeeqG39Of+rlWncJFnFPkKvkSERcX+fnRf3bVNd0JTejRtmGi9WsI2GemC3B4G9D6A+31kNkrCB8blFLJBKMgK5L5VJNuiVoJrbUAweQQwwfOuydQQkveQbPSuHxzkEfsCnk/70YVYydgfPsMzrxnY0SNCA="
